name: desafio_variacao_ativo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: 5.0.0
  get: 4.6.5
  dartz: 0.10.1
  pretty_dio_logger: 1.3.1
  collection: 1.17.0
  intl: 0.18.0
  yahoofin: 0.0.8
  fl_chart: 0.61.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

